insert into report (id, deadline, description, title, internship_id)
values (1,
        '2024-08-31',
        'Le résumé de votre expérience au sein de l\'entreprise, et comprend des informations sur les compétences, les connaissances et les informations acquises pendant cette immersion professionnelle.',
        'Rapport de stage',
        1),
       (2,
        '2024-08-31',
        'Le résumé de votre expérience au sein de l\'entreprise, et comprend des informations sur les compétences, les connaissances et les informations acquises pendant cette immersion professionnelle.',
        'Rapport de stage',
        2),
       (3,
        '2024-02-28',
        'Le résumé de votre expérience au sein de l\'entreprise, et comprend des informations sur les compétences, les connaissances et les informations acquises pendant cette immersion professionnelle.',
        'Rapport de stage',
        3),
       (4,
        '2024-10-31',
        'Le résumé de votre expérience au sein de l\'entreprise, et comprend des informations sur les compétences, les connaissances et les informations acquises pendant cette immersion professionnelle.',
        'Rapport de stage',
        4),
       (5,
        '2024-09-30',
        'l’aboutissement d’un cursus universitaire validant votre diplôme de fin d’études. Il se présente sous la forme d’un document écrit de 50 à 100 pages respectant des normes formelles et rédactionnelles spécifiques.',
        'Mémoire',
        5),
       (6,
        '2024-09-30',
        'Oral de soutenance de votre stage',
        'Soutenance',
        1),
       (7,
        '2024-09-30',
        'Oral de soutenance de votre stage',
        'Soutenance',
        2),
       (8,
        '2024-04-30',
        'Oral de soutenance de votre stage',
        'Soutenance',
        3),
       (9,
        '2024-11-30',
        'Oral de soutenance de votre stage',
        'Soutenance',
        4),
       (10,
        '2024-09-30',
        'Oral de soutenance de votre stage',
        'Soutenance',
        5),
       (11,
        '2024-02-28',
        'Rapport de milieu de stage de fin d\'année',
        'Rapport de milieu de stage',
        5),
       (12,
        '2024-09-30',
        'Cahier des charges de votre projet de fin d\'études',
        'Cahier des charges',
        5),
       (13,
        '2024-09-30',
        'Cahier des charges de votre projet de fin d\'études',
        'Cahier des charges',
        4);
